title: avalanches.wtf
  avatar: "https://raw.githubusercontent.com/gvcxm2j5KQbrnl/avalanches.wtf/refs/heads/main/assets/logo.png"
theme: minima
author: gvcxm2j5KQbrnl
plugins:
  - jekyll-feed

permalink: /blog/:title/
