title: avalanches.wtf
theme: minima
author: 
  name: gvcxm2j5KQbrnl
  avatar: "https://raw.githubusercontent.com/gvcxm2j5KQbrnl/avalanches.wtf/refs/heads/main/assets/logo.png"
plugins:
  - jekyll-feed

permalink: /blog/:title/
